[package]
name = "slepc-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# petsc-sys = { path = "../petsc-sys" }

[build-dependencies]
build-probe-mpi = "0.1"
bindgen = "0.55"
